### ISSUE TITLE
Inotify implementation doesn't remove subdirectories after remove_directory

### ISSUE THREAD

**Issue by GamePad64** [berkus/dir_monitor#13]
I have directory structure like this:
dir1
|
+- dir2
After running remove_directory("dir1") events in "dir1" are not catched, but events in "dir2" continue to be catched. Is it a bug or feature?

**Comment by obaskanderi** [comment]
That's a bug. I do have a patch for it in my fork sorry haven't created a PR for it, I will.

**Comment by obaskanderi** [comment]
https://github.com/berkus/dir_monitor/pull/14

**Comment by berkus** [comment]
Fixed by PR #15
