### ISSUE TITLE
exceptions thrown from boost::asio::basic_dir_monitor_service<boost::asio::dir_monitor_impl>::work_thread() cannot be caught from the main thread

### ISSUE THREAD

**Issue by rockonedege** [berkus/dir_monitor#21]
I encountered uncaught exceptions be thrown from boost::asio::basic_dir_monitor_service<boost::asio::dir_monitor_impl>::work_thread() Line 218 in Windows. As enlightened by this [link](http://stackoverflow.com/questions/233127/how-can-i-propagate-exceptions-between-threads), and study the the current implementation, work_thread()  is running in its own thread, thus the exceptions being thrown cannot be caught from any other thread. Can you please confirm this is correct? If yes, I'd like to fix it as the above [link](http://stackoverflow.com/questions/233127/how-can-i-propagate-exceptions-between-threads) suggest. I'll be better if you have test cases for exceptions.

**Comment by berkus** [comment]
Hi, I will try and add exceptions test cases when I have some time.

**Comment by rockonedege** [comment]
It turns out in my case(monitoring a mapped windows drive half a world away),  work_thread() throws exceptions easily suffering from slow networking.

I've been thinking about how to transfer the exceptions in work_thread() to the main thread so as to catch them, but could not find a way. 

If you have any specific ideas in mind,  I might find time to get it implemented and send it for your review.

**Comment by berkus** [comment]
I will take a closer look at this today then.

**Comment by lucasvickers** [comment]
FWIW I'm interested in this as well. Will help if there's anything to assist with.

**Comment by rockonedege** [comment]
Thanks. While I am typing, It occurred to me that we could expose the thread handle(e.g. get_work_thread()) so that it could joined later from the caller site, then the exceptions could be caught following [the pattern in this link](http://stackoverflow.com/questions/233127/how-can-i-propagate-exceptions-between-threads). However I do not like this idea much as it's more a hack to facilitate the implementation itself rather than a natural need/facility/interface of directory monitoring.

**Comment by sbelsky** [comment]
hello collegues. my recently attempts of using this project has given me the similar result.
i don't think that "exceptions between threads propagation" is best solution for this class. let's explain why.

##### consider the following example
there are N+1 folders for monitoring task: remote temp (shared via smb) and local temp1, temp2, ... , tempN.
1. in windows command line console type "net use {url_to_remote_temp} {password} /USER:{login}"
2. start for execution something like
```cpp
boost::asio::dir_monitor monitor(io_service);
monitor.add_directory(<path_to_shared_temp>);
monitor.add_directory(<path_to_local_temp1>);
monitor.add_directory(<path_to_local_temp2>);
...
monitor.add_directory(<path_to_local_tempN>);

for (;;)
{
    monitor.async_monitor(some_handler);
    io_service.run();
}
```
3.in windows cmd type "net use {url_to_remote_temp1} /DELETE"

and we have an exception from [Line 218](https://github.com/berkus/dir_monitor/blob/master/include/windows/basic_dir_monitor_service.hpp#L218) caused by ```ERROR_OPERATION_ABORTED``` code returned from ```GetQueuedCompletionStatus``` function from [Line 213](https://github.com/berkus/dir_monitor/blob/master/include/windows/basic_dir_monitor_service.hpp#L213).
##### What can we conclude? 
1. Unhandled exception leads to app crash
2. One problem directory leads fail on whole monitoring task. 

so, my conclusions are:
1. work_thread() must not throw any exception and it should continue to work
2. we can process ```ERROR_OPERATION_ABORTED``` return code. In this case ```GetQueuedCompletionStatus``` set ```ck``` with proper completion port value and ```bytes_transferred``` with 0. So at least we will come to [Line 225](https://github.com/berkus/dir_monitor/blob/master/include/windows/basic_dir_monitor_service.hpp#L225).

in addition, i'm going to share my solution with pull request soon.

**Comment by sbelsky** [comment]
```
CMake Error at CMakeLists.txt:6 (cmake_minimum_required):
  CMake 3.1 or higher is required.  You are running version 2.8.7
```
in CI build :disappointed_relieved:

**Comment by berkus** [comment]
Yeah, CI has problems still.. Couldn't find time to configure it all correctly there.

**Comment by rockonedege** [comment]
FWIW, there's still the value of throwing when something goes wrong with the directories be monitored, so that I know what going on. 

I am wondering if we can put the io_service.run() into dir_monitor.  and the client code looks something like this:
```

try
{
    boost::asio::dir_monitor monitor(io_service);
    monitor.add_directory(<path_to_shared_temp>);
    monitor.add_directory(<path_to_local_temp1>);
    monitor.add_directory(<path_to_local_temp2>);
    // ...
    monitor.add_directory(<path_to_local_tempN>);

    monitor.async_monitor(some_handler);

    // internally it delegates to io_serivce.run(), 
    // and **collects  and re-thows** all exceptions from spawned threads
    monitor.run(); 
}
catch (/*all exceptions*/)
{
   // handlers or even recreate a new boost::asio::dir_monitor object
}

```


the down

**Comment by sbelsky** [comment]
@rockonedege the main downside of your "run" offer is that it doesn't match asio conceptions.

in addition to my previous arguments throwing exception doesn't give us a chance to deallocate memory for ```ck``` in case of error or ```remove_directory``` calling.

**Comment by rockonedege** [comment]
@sbelsky, sorry for the late response. Your points against my previous wild thoughts are valid. 

I finally succeed in achieving 3 goals:
- keep the throwing mechanism
- stick to `asio` conventions on exception handling
- keep the io service and its work_thread() method in good health after exceptions.

The main idea being:
- transfer the exceptions inside basic_dir_monitor_service::work_thread() to basic_dir_monitor_service::thread_exception_ptr_
-  add basic_dir_monitor_service::throw_me() to rethrow basic_dir_monitor_service::thread_exception_ptr_
- post basic_dir_monitor_service::throw_me() to the owner(i.e. base class) of basic_dir_monitor_service.

then at the client,  the code would be like this:
~~~cpp

	io_service io_service;

	dir_monitor monitor(io_service);
	monitor.add_directory(...);
    monitor.async_monitor(some_handler);
	
	for (;;)
	{
		try 
		{
			cout << "Monitoring service started:\n";
			io_service.run();
		}
		catch (const boost::system::system_error& e)
		{
			// do whatever with the exceptions thrown from basic_dir_monitor_service::work_thread()	
		}
	}
~~~

The code has been committed to [my fork](). 
I haven't figure out how to write the test.  However,  if you replace the committed `basic_dir_monitor_service::work_thread()` with the following the code, you'll see it works perfectly.
~~~cpp

    // this code throws at first run and then goes back to normal to show that 
    // the service can actually survive exceptions and continues to work
    void work_thread()
    {
        static int i = 0;
        while (running())
        {
            try
            {
                if (i == 0)
                {
                    ++i;

                    boost::system::system_error e(boost::system::error_code(0x40, boost::system::get_system_category()), "hello moto");
                    boost::throw_exception(e);

                }

                work();
            }
            catch (...)
            {
                thread_exception_ptr_ = std::current_exception();
                this->get_io_service().post(boost::bind(&boost::asio::basic_dir_monitor_service<DirMonitorImplementation>::throw_me, this));
            }
        }
    }  
~~~

@berkus, if you are ok with this implementation, I can create a pull request.

**Comment by berkus** [comment]
Please, make a PR and I'll review, will be more handy like that.

**Comment by sbelsky** [comment]
@rockonedege ooo I didn't assume that it is possible to do
```
boost::bind(&boost::asio::basic_dir_monitor_service<DirMonitorImplementation>::throw_me, this));
```
generally it seems to me this is a good approach.
