### ISSUE TITLE
Why is you work_thread_ in windows/service instead of windows/impl?

### ISSUE THREAD

**Issue by lucasvickers** [berkus/dir_monitor#26]
In all examples except windows you have your ```work_thread_``` in the ```basic_dir_impl.hpp```.  In windows you have this inside of your ```basic_dir_monitor_service.hpp``` and only use your ```dir_monitor_impl.hpp``` to manage your containers such as:
```boost::ptr_unordered_map<std::string, windows_handle> dirs_;```

Is there an explicit reason for this?

Thank you!

**Comment by berkus** [comment]
I don't know an explicit reason, this code was inherited from Boris Schaelig original version.

I'm pretty sure it could be refactored into a better shape. Actually we're doing this right now while fixing some cross-thread exception issues.

**Comment by lucasvickers** [comment]
Thanks for the reply.  I didn't think there was a reason, but wanted to double check.
