### ISSUE TITLE
Move everything from include/ into include/dir_monitor/

### ISSUE THREAD

**Issue by GamePad64** [berkus/dir_monitor#29]
All the libraries I saw had their headers in a nested folder in include/.
It is done for making them available as `<dir_monitor/dir_monitor.hpp>`, for example.

Maybe, we should consider moving headers in a nested folder, too?

**Comment by berkus** [comment]
Sounds ok to me, I use the same structure in my projects anyway. What's the common **boost** practice?

**Comment by sbelsky** [comment]
+1 this is a good modern code style.
@berkus boost project uses the same structure.
