### ISSUE TITLE
Project need more advanced CM model

### ISSUE THREAD

**Issue by sbelsky** [berkus/dir_monitor#38]
@berkus 
Working with this repository, I have encountered several times that codebase was in an invalid state.
For example look at the last fail situation: [changes which were broken CI](https://github.com/berkus/dir_monitor/commit/b6ab3857f163b293a71ceaa6918b07e7dc2802eb)

My offer is to implement more safily workflov. Nothing complicated, just "master-develop" model.
As illustation: http://nvie.com/posts/a-successful-git-branching-model/#the-main-branches
1. all works should take a place at branch's of develop
2. all PR should be requested to develop branch. branching from master should be prohibited.
3. project owner sometimes merges to master. when there is confidence in the stability of the code.
   Also it would be nice to start project versioning.

**Comment by berkus** [comment]
Agree. I used this only personally before so there wasn't need to make more branches, but since there are multiple contributors, having versions and stable/unstable branches seems fair.

**Comment by sbelsky** [comment]
always nice when your project is demended ;)

**Comment by berkus** [comment]
Created `develop` branch and added `v1.0.0` release https://github.com/berkus/dir_monitor/releases

**Comment by berkus** [comment]
Should we add some kind of version `#define` in the code as well?

**Comment by sbelsky** [comment]
do you mean something like version.h ? i think yes.

**Comment by uilianries** [comment]
you could use CMake to generate this: https://cmake.org/cmake-tutorial/#s1
