### ISSUE TITLE
Can't compile under windows with VC++

### ISSUE THREAD

**Issue by rockonedege** [berkus/dir_monitor#7]
line #255(\include\windows\basic_dir_monitor_service.hpp) throws error under windows as `class dir_monitor_event` has no constructor accepting 3 parameters.  Deleting the first parameter will let go, but I do not know the impact without further understanding the internals.

**Comment by berkus** [comment]
I'll need to test in newer VS, one I have doesn't support lambdas. ¯\_(ツ)_/¯

**Comment by rockonedege** [comment]
It's not related to lambda, but a signature mismatch, there's no such an overloaded ctor. I guess there was one, but refactored out later.

**Comment by berkus** [comment]
I know. I just cannot compile this code with my VS, so cannot verify and make a fix for you now.

**Comment by rockonedege** [comment]
I see. I solved my problem by forcing the match of signature at the caller, which may bring side effects. Before you have time to see to it. It might be useful to others using the code.

**Comment by berkus** [comment]
Can you post your patch here?

**Comment by berkus** [comment]
Or make a pull-request.

**Comment by rockonedege** [comment]
Git newbie here. Will do after I figure out how.

**Comment by berkus** [comment]
No pressure.

**Comment by berkus** [comment]
Should be fixed now, reopen if you still have troubles with compiling.
